### ISSUE TITLE
Beauty Awards裡的產品都沒有加上正確連結

### ISSUE THREAD

**Issue by LandyHsiao** [LandyHsiao/beauty-hub#80]
https://github.com/LandyHsiao/beauty-hub/blob/ce24f1bf9ef9527e078d391ae6420d56916f3f7f/pages/beauty_awards.html#L34
@cestJessie

**Comment by jccodeob1o** [comment]
連去你做的產品頁面？？

**Comment by LandyHsiao** [comment]
對 沒有對應頁面的話起碼要連到 product_01

**Comment by jccodeob1o** [comment]
痾 我是覺得這樣很怪啦 連到不同的產品頁面 如果你要加可以自己加喔

**Comment by LandyHsiao** [comment]
Ok那就不加
這個issue我就結掉了
